version: "2"
services:
  jenkins:
    build:
      context: .
      args:
        gituser: "${PIPELINE_GIT_USERNAME}"
        gitpass: "${PIPELINE_GIT_PASSWORD}"
    ports:
      - "9090:8080"
    volumes:
      - /var/jenkins_home
    links:
      - artifactory
  artifactory:
    image: jfrog-docker-registry.bintray.io/artifactory/artifactory-oss:latest
    ports:
      - "9091:8081"
